export const DEFAULT_THEME = 'main';
export const DARK_THEME = 'dark';
export const DARK_THEME_TEXT = 'darkText';
export const DARK_THEME_BODY = 'darkBody'
export const GAME_NAME = 'React Tic Tac Toe';
export const NEW_GAME = 'New Game';
export const RETURN = 'Return';
export const GAME_OVER_MESSAGE = 'Game Over';
export const PLAYER1 = 'Player 1 (X)';
export const PLAYER2 = 'Player 2 (O)';
export const EDIT_MODE = 'Edit';
export const SAVE_MODE = 'Save'
export const TURN_PLAYER1 = 'X';
export const TURN_PLAYER2 = 'O';
export const INITIAL_TILE_NUMBER = 9;
export const TIE_MESSAGE = 'It is a tie!';
export const BACKGROUND_COLOR_DARK = '#2E3440';
export const BACKGROUND_APP_DARK = '#16181d';
export const BACKGROUND_COLOR_LIGHT = 'rgb(255, 255, 255)';
export const TEXT_DARK = 'rgb(255, 255, 255)';
export const TEXT_LIGHT = 'rgb(8 126 164 )';
export const TEXT_O_LIGHT = '#2E3440';